### ISSUE TITLE
DFCT0010086 | Test GitHub New Flow Labels | 02

### ISSUE THREAD

**Issue by ServiceNowSpoke** [CrisLigX/EYgitHubTest#112]
Test GitHub New Flow Labels | 02

**Comment by CrisLigX** [comment]
[#SNFLOW#] 2022-04-22 06:47:39 - Cristian Angelo Liguori (Work notes)
Prova 1

**Comment by CrisLigX** [comment]
Prova 2

**Comment by CrisLigX** [comment]
[#SNFLOW#] 2022-04-22 06:47:56 - Cristian Angelo Liguori (Work notes)
Prova 3

**Comment by CrisLigX** [comment]
Close comment
