### ISSUE TITLE
DFCT0010172 | Defect Test New Flo

### ISSUE THREAD

**Issue by BernatNosasAmplifon** [CrisLigX/EYgitHubTest#92]
Prova

**Comment by CrisLigX** [comment]
Prova 2

**Comment by BernatNosasAmplifon** [comment]
[#SNFLOW#] 2022-04-04 05:20:43 - Guest (Work notes)
Prova 2

**Comment by BernatNosasAmplifon** [comment]
[#SNFLOW#] 2022-04-04 05:20:48 - Cristian Angelo Liguori (Work notes)
Prova 3

**Comment by CrisLigX** [comment]
Close comment

**Comment by BernatNosasAmplifon** [comment]
[#SNFLOW#] 2022-04-04 05:21:19 - Guest (Work notes)
Close comment
